authorization.authorization_profile.*:
  type: config_entity
  label: 'Authorization profile config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    provider:
      type: string
      label: 'Provider Plugin ID'
    provider_config:
      type: authorization.provider.plugin.[%parent.provider]
      label: 'Provider configuration'
    consumer:
      type: string
      label: 'Consumer Plugin ID'
    consumer_config:
      type: authorization.consumer.plugin.[%parent.consumer]
      label: 'Consumer configuration'
    status:
      type: boolean
      label: 'Enabled'
