authorization.authorization_profile.*:
  type: config_entity
  label: 'Authorization profile config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    provider:
      type: string
      label: 'Provider'
    consumer:
      type: string
      label: 'Consumer'
    status:
      type: boolean
      label: 'Enabled'
